In [129]:
import numpy as np
import matplotlib.pyplot as plt

In [130]:
R=np.array(([0.728027761,-0.525104821,0.440727293],
[0.608788550, 0.790790558, -0.063456595],
[-0.315201640, 0.314507872, 0.895395279]))

In [170]:
def puissance(A, epsilon, max_iterations):
    x = np.array((1.0, 2.0, 3.0))
    n = A.shape[0]
    x = x / np.linalg.norm(x)  # Normalisation du vecteur initial
    for i in range(max_iterations):
        y = A.dot(x)  # Produit matrice-vecteur
        eigenvalue = np.dot(x, y)  # Estimation de la valeur propre dominante
        x = y / np.linalg.norm(y)  # Normalisation du vecteur propre
        # Critère de convergence
        if np.linalg.norm((A.dot(x) - eigenvalue * x),2) < epsilon:
            break
    return eigenvalue, x

# Exemple d'utilisation
epsilon = 1e-7  # Tolérance pour la convergence
max_iterations = 100  # Nombre maximum d'itérations

eigenvalue, eigenvector = puissance(R, epsilon, max_iterations)
print("Valeur propre dominante:", eigenvalue)
print("Vecteur propre correspondant:", eigenvector)

Valeur propre dominante: 0.999999970214286
Vecteur propre correspondant: [0.26726125 0.53452247 0.80178373]


In [143]:
import numpy as np
from scipy.linalg import lu

def puissance_inv(A, max_iterations=1, tolerance=1e-7):
    n = A.shape[0]
    P,L, U = lu(A)
    z0 = np.dot(L,np.ones((n)))
    print (z0)
    z0_=z0/np.linalg.norm(z0, ord=2)
    for i in range(max_iterations):
        y = np.linalg.solve(L, z0)
        w = np.linalg.solve(U, y)
        z = w / np.linalg.norm(w, ord=2)  # Normalization
        if np.linalg.norm(z - z0_) < tolerance:
            break
        z0=z
        z0_=z0/np.linalg.norm(z0, ord=2)
        lamda = 1/np.dot(z0_.T, z)
    return lamda, z0

# Exemple d'utilisation
s=1.0001
B= R-s*np.eye(3)
eigenvalue_inv, eigenvector_inv = puissance_inv(B)
print("Inverse Eigenvalue:", eigenvalue_inv)
print("Inverse Eigenvector:", eigenvector_inv)

s=0.9999
B= R-s*np.eye(3)
eigenvalue_inv, eigenvector_inv = puissance_inv(B)
print("Inverse Eigenvector:", eigenvector_inv)

[1.         0.55309238 0.14904077]
Inverse Eigenvalue: 1.0
Inverse Eigenvector: [-0.26717367 -0.5346189  -0.80174863]
[1.         0.55342091 0.14878818]
Inverse Eigenvector: [0.26734885 0.53442605 0.8018188 ]


In [138]:
T= np.array((1.0, 2.0, 3.0))/np.linalg.norm(np.array((1.0, 2.0, 3.0)), ord=2)

In [156]:
vi=np.dot(L,np.ones((3)))
vi=vi/np.linalg.norm(vi,ord=2)
y1 = np.linalg.solve(L, vi)
v = np.linalg.solve(U, y1)
v1=v/np.linalg.norm(v,ord=2)

In [168]:
vi=v1
vi=vi/np.linalg.norm(vi,ord=2)
y1 = np.linalg.solve(L, vi)
v = np.linalg.solve(U, y1)
v1=v/np.linalg.norm(v,ord=2)

In [171]:
v1

array([0.02057132, 0.92422875, 0.38128473])

In [172]:
R

array([[ 0.72802776, -0.52510482,  0.44072729],
       [ 0.60878855,  0.79079056, -0.0634566 ],
       [-0.31520164,  0.31450787,  0.89539528]])